<<<<<<< HEAD
[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
=======
# config
>>>>>>> 060e6e5b36d5fda50d2fd118ec2421bf623d1b32
